# Netlify configuration for form handling
[build]
  publish = "dist"

# Form submission settings
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules for form success
[[redirects]]
  from = "/success"
  to = "/success"
  status = 200

# Form handling configuration
[[forms]]
  name = "event-registration"
